# Generated by Django 2.1.2 on 2019-01-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('pic_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_posted', models.DateTimeField(verbose_name='date posted')),
                ('date_taken', models.DateTimeField(verbose_name='date taken')),
                ('date_updated', models.DateTimeField(verbose_name='date updated')),
                ('view_count', models.IntegerField(verbose_name='views')),
                ('source_url', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('wallpaper', models.BooleanField(default=False)),
            ],
        ),
    ]
