# Generated by Django 2.1.2 on 2019-01-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('public_pics', models.IntegerField(verbose_name='public_pics')),
                ('total_pics', models.IntegerField(verbose_name='total_pics')),
                ('view_count', models.IntegerField(verbose_name='view_count')),
                ('edits', models.IntegerField(verbose_name='edits')),
            ],
        ),
    ]
