# Generated by Django 2.1.2 on 2019-01-17 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
