# Generated by Django 2.1.2 on 2019-01-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_auto_20190117_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
