# Generated by Django 2.1.2 on 2019-01-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0004_auto_20190117_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name_plural': 'Statistics'},
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='total_pics',
        ),
    ]
