# Generated by Django 2.1.2 on 2019-02-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0005_auto_20190117_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoWallpaper',
            fields=[
                ('pic_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Exclude from wallpaper',
            },
        ),
    ]
